# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Control Plane Provider Talos"
github_repo = "talos-systems/cluster-api-control-plane-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.3.0"

pre_release = false

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1alpha4"
        description = """\
This release of CACPPT brings compatibility with CAPI v1alpha4.

Support new conditions, which should simplify CABPT issues debugging:
- `MachinesReady` reports an aggregate of current status of the machines controlled by the TalosControlPlane.
- `Available` the first control plane instance has completed Talos boot sequence and so the control plane is available and an API server instance is ready for processing requests.
- `Resized` TalosControlPlane is resizing the set of controlled machines.
- `ControlPlaneComponentsHealthy` reports the overall status of control plane components implemented as static pods generated by Talos including kube-api-server, kube-controller manager, kube-scheduler and etcd.
- `EtcdClusterHealthyCondition` overall etcd cluster's health.
- `MachinesCreated` the machines controlled by the TalosControlPlane are created.

"""
