# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Control Plane Provider Talos"
github_repo = "talos-systems/cluster-api-control-plane-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.0"

pre_release = true

preface = """\
"""

[notes]

    [notes.rolling-update]
        title = "Trigger Rolling Updates on Talos Config Changes"
        description = """\
The controller now reacts to `TalosConfig` spec changes
and can do rolling updates of the control plane machines.
"""
