# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Control Plane Provider Talos"
github_repo = "talos-systems/cluster-api-control-plane-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.4"

pre_release = false

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1beta1"
        description = """\
This release of CACPPT is compatible with CAPI v1beta1 (v1.x).
"""
  
    [notes.rolling-update]
        title = "Support Control Plane Rolling Updates"
        description = """\
The controller now reacts to `TalosControlPlane` spec changes
and can do rolling updates of the control plane machines.
This can be used to do a graceful upgrades of the workload clusters.
"""
